---
- name: Gather OS facts
  ansible.builtin.setup:
    gather_subset: distribution

- name: Add Docker apt repo
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  register: docker_repo

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: "{{ docker_repo.changed }}"

- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group {{ t3_user }}
  ansible.builtin.user:
    name: "{{ t3_user }}"
    groups: docker
    append: true
