services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "homepage.group=Management"
      - "homepage.name=Portainer"
      - "homepage.icon=sh-portainer"
      - "homepage.href=https://192.168.2.100:9443"
volumes:
  data:
