networks:
  traefik:
    external: true

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/nas/media/books:/config/Calibre Library
    ports:
      - 12000:8080
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Calibre
      - homepage.icon=calibre.png
      - homepage.showStats=false
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:12000

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    extends:
      file: ../base.yml
      service: base
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /mnt/docker/calibre-web:/config
      - /mnt/nas/media/books:/books
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Calibre Web
      - homepage.icon=calibre-web.png
      - homepage.showStats=false
      - homepage.href=https://books.homelab.fahimshahreer.com
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`books.homelab.fahimshahreer.com`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.docker.network=traefik"

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   extends:
  #     file: ../base.yml
  #     service: base
  #   volumes:
  #     - /mnt/docker/readarr:/config
  #     - /mnt/nas/media/books:/books
  #     - /mnt/downloads:/downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   labels:
  #     - homepage.group=Arrs
  #     - homepage.name=Readarr
  #     - homepage.icon=readarr.png
  #     - homepage.showStats=false
  #     - homepage.href=http://bromine.fenrir-cardassian.ts.net:8787

