---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
      - VERSION=docker
      - PLEX_CLAIM=claim-9wxn7nnhdprze6ci4FtN
    volumes:
      - /mnt/docker/plex:/config
      - /mnt/nas/media/tv:/tv
      - /mnt/nas/media/movies:/movies
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=sh-plex
      - homepage.showStats=true
      - homepage.href=http://192.168.2.100:32400
      - homepage.widget.type=plex
      - homepage.widget.url=http://192.168.2.100:32400
      - homepage.widget.key=GWUxGJgdnUzPLHT9HCwV
      - homepage.widget.fields=["streams", "albums", "movies", "tv"]
