networks:
  arr-seerr:
    external: true
  traefik:
    external: true

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    networks:
      - traefik
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "33400:33400/tcp"
    volumes:
      - /mnt/docker/plex:/config
      - /mnt/nas/media:/nas
      # - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: "America/Toronto"
      HOSTNAME: "Bromine"
      # PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_CLAIM: "claim-4_XXTxwdGpeK4zvgJ5H4"
      PLEX_UID: 1001
      PLEX_GID: 1001
      # ADVERTISE_IP: "http://$MEDIASERVER_IP:32400/,http://$ZEROTIER_IP_MEDIASERVER:32400/,https://proxplex.$DOMAINNAME_HS"
      ALLOWED_NETWORKS: 192.168.2.0/24
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.showStats=true
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:32400
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`watch.homelab.fahimshahreer.com`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=traefik"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/docker/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - homepage.group=Monitoring
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:8181
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`watchstats.homelab.fahimshahreer.com`)"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.docker.network=traefik"

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/docker/overseerr:/config
    ports:
      - 5056:5055
    networks:
      - traefik
      - arr-seerr
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:5056
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`request.homelab.fahimshahreer.com`)"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik"

  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    extends:
      file: ../base.yml
      service: base
    environment:
      - KOMETA_CONFIG=/mnt/docker/kometa
      - KOMETA_TIME=03:00
      - KOMETA_RUN=False #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - /mnt/docker/kometa:/config
    restart: unless-stopped
