networks:
  arr-overseerr:
    external: true
  traefik:
    external: true

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    extends:
      file: ../base.yml
      service: base
    environment:
      - VERSION=docker
      - PLEX_CLAIM=claim-sFw4K3nnQ3xuV22jY88F
    volumes:
      - /mnt/docker/plex:/config
      - /mnt/nas/media/tv:/tv:ro
      - /mnt/nas/media/movies:/movies:ro
    ports:
      - 32400:32400  
      # - 1900:1900
      # - 5353:5353
      # - 8324:8324
      # - 32410:32410
      # - 32412:32412
      # - 32413:32413
      # - 32414:32414
      # - 32469:32469
    networks:
      - traefik
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.showStats=true
      - homepage.href=http://192.168.2.100:32400
      - homepage.widget.type=plex
      - homepage.widget.url=http://192.168.2.100:32400
      - homepage.widget.key=GWUxGJgdnUzPLHT9HCwV
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.fahimshahreer.com`)"
      - "traefik.http.routers.plex.entrypoints=web"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/docker/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=http://192.168.2.100:8181

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/docker/overseerr:/config
    ports:
      - 5055:5055
    networks:
      - traefik
      - arr-overseerr
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=http://192.168.2.100:5055
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.fahimshahreer.com`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
