networks:
  traefik:
    external: true

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      - traefik
    ports:
      - 13378:80
    user: 1001:1001
    volumes:
      - /mnt/nas/media/audiobooks:/audiobooks
      - /mnt/nas/media/podcasts:/podcasts
      - /mnt/nas/appdata/audiobookshelf:/metadata
      - /mnt/docker/audiobookshelf/config:/config
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Audiobookshelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=http://192.168.2.100:13378
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`audiobooks.fshrr.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
