---
- name: Add GitHub CLI apt repo
  ansible.builtin.deb822_repository:
    name: github-cli
    types: deb
    uris: https://cli.github.com/packages
    suites: stable
    components: main
    architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present

- name: Install gh
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
    cache_valid_time: 3600
