networks:
  traefik:
    external: true
  arr-seerr:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    extends:
      file: ../base.yml
      service: base
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /mnt/docker/jellyfin:/config
      - /mnt/nas/media/:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.showStats=true
      - homepage.href=http://192.168.2.100:8096
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`watch.fshrr.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=traefik"

  jellyseerr: 
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr 
    hostname: jellyseerr 
    extends:
      file: ../base.yml
      service: base
    environment:
      - UMASK=002
    ports: 
      - 5055:5055 
    networks:
      - traefik
      - arr-seerr
    volumes: 
      - /mnt/docker/jellyseerr:/app/config 
    restart: unless-stopped 
    labels:
      - "homepage.group=Arrs"
      - "homepage.name=Jellyseerr"
      - "homepage.icon=jellyseerr.png"
      - "homepage.href=http://192.168.2.100:5055"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`request.fshrr.com`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik"
