services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    extends:
      file: ../base.yml
      service: base
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /mnt/docker/jellyfin:/config
      - /mnt/nas/media/movies:/movies:ro
      - /mnt/nas/media/tv:/tv:ro
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.showStats=true
      - homepage.href=http://192.168.2.100:8096
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.fahimshahreer.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"

  jellyseerr: 
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    user: 1001:1001
    environment: 
      - TZ=America/Toronto 
    ports: 
      - 5056:5055 
    networks:
      - traefik
    volumes: 
      - /mnt/docker/jellyseerr:/app/config 
    restart: unless-stopped 
    labels:
      - "homepage.group=Arrs"
      - "homepage.name=Jellyseerr"
      - "homepage.icon=sh-jellyseerr"
      - "homepage.href=http://192.168.2.100:5056"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.fahimshahreer.com`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"

networks:
  traefik:
    external: true
