networks:
  traefik:
    external: true
  open-webui:
    driver: bridge

volumes:
  open-webui:

services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - traefik
      - open-webui
    ports:
      - "8050:8080"
    volumes:
      - open-webui:/app/backend/data
    labels:
      - homepage.group=Personal
      - homepage.name=Open WebUI
      - homepage.icon=open-webui-light.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:8050
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.openwebui.rule=Host(`chat.homelab.fahimshahreer.com`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.service=openwebui"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
  
  mcpo:
    container_name: mcpo
    image: ghcr.io/open-webui/mcpo:main
    networks:
      - open-webui
    volumes:
      - /mnt/docker/open-webui/mcpo-config.json:/app/config.json
    command: ["mcpo", "--config", "/app/config.json"]
