services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1001
      PGID: 1001
    networks:
      - docker-socket-proxy
    ports:
      - 3000:3000
    volumes:
      - /mnt/docker/homepage:/app/config
    restart: unless-stopped

networks:
  docker-socket-proxy:
    external: true
