networks:
  arr:
    external: true

volumes:
  lidarr_data:
    driver: local
  slskd_data:
    driver: local
  soularr_data:
    driver: local

services:
  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    extends:
      file: ../base.yml
      service: base
    networks:
      - arr
    volumes:
      - lidarr_data:/config
      - ${MUSIC_PATH}:/music
      - ${SLSKD_DOWNLOADS_PATH}:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:8686

  slskd:
    image: slskd/slskd
    container_name: slskd
    hostname: slskd
    user: 1001:1001
    extends:
      file: ../base.yml
      service: base
    networks:
      - arr
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    volumes:
      - slskd_data:/app
      - ${SLSKD_DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
    labels:
      - homepage.group=Download Clients
      - homepage.name=Slskd
      - homepage.icon=slskd.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:5030

  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    hostname: soularr
    user: 1001:1001
    extends:
      file: ../base.yml
      service: base
    networks:
      - arr
    environment:
      - SCRIPT_INTERVAL=300
    volumes:
      - ${SLSKD_DOWNLOADS_PATH}:/downloads
      - soularr_data:/data
    restart: unless-stopped
