# prowlarr.yml
networks:
  arr:
    external: true
  arr-seerr:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - arr
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://bromine.fenrir-cardassian.ts.net:9696
