services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=1001
      - PGID=1001
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Toronto
    ports:
      - 8191:8191
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=flaresolverr
      - homepage.icon=flaresolverr.png
      - homepage.href=http://192.168.2.100:8191

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8090:8090
    environment:
      - VPN_SERVICE_PROVIDER=privado
      - OPENVPN_USER=nhnwfixvdiio
      - OPENVPN_PASSWORD=p!2o7L#2668%fx
    volumes:
      - /mnt/docker/gluetun:/gluetun
      # - ./client.key:/gluetun/client.key
      # - ./client.crt:/gluetun/client.crt
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
      - WEBUI_PORT=8090
    volumes:
      - /mnt/docker/qbittorrent:/config
      - /mnt/downloads:/downloads 
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    labels:
      - homepage.group=Download Clients
      - homepage.name=qbittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://192.168.2.100:8090
