# torrent.yml
networks:
  arr:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    extends:
      file: ../base.yml
      service: base
    cap_add:
      - NET_ADMIN
    ports:
      - 9090:9090
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - arr
    environment:
      - VPN_SERVICE_PROVIDER=privado
      - OPENVPN_USER=nhnwfixvdiio
      - OPENVPN_PASSWORD=p!2o7L#2668%fx
    volumes:
      - ${APPDATA_PATH}/gluetun:/gluetun
      # - ./client.key:/gluetun/client.key
      # - ./client.crt:/gluetun/client.crt
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    extends:
      file: ../base.yml
      service: base
    environment:
      - WEBUI_PORT=9090
    volumes:
      - ${APPDATA_PATH}/qbittorrent:/config
      - ${DOWNLOADS_PATH}:/downloads 
    depends_on:
      - gluetun
    network_mode: container:gluetun
    restart: unless-stopped
    labels:
      - homepage.group=Download Clients
      - homepage.name=qbittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://192.168.2.100:9090

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    extends:
      file: ../base.yml
      service: base
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - 8191:8191
    networks:
      - arr
    restart: unless-stopped
    labels:
      - homepage.group=Arrs
      - homepage.name=Flaresolverr
      - homepage.icon=flaresolverr.png
      - homepage.href=http://192.168.2.100:8191
