services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /mnt/docker/sabnzbd:/config
      - /mnt/downloads:/downloads
      - /mnt/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - homepage.group=Download Clients
      - homepage.name=sabnzbd
      - homepage.icon=sabnzbd.png
      - homepage.href=http://192.168.2.100:8080

  #nzbget:
  #  image: lscr.io/linuxserver/nzbget:latest
  #  container_name: nzbget
  #  environment:
  #    - PUID=1001
  #    - PGID=1001
  #    - TZ=America/Toronto
  #  volumes:
  #    - /mnt/docker/nzbget:/config
  #    - /mnt/downloads:/downloads
  #  ports:
  #    - 6789:6789
  #  restart: unless-stopped
  #  labels:
  #    - homepage.group=Download Clients
  #    - homepage.name=nzbget
  #    - homepage.icon=nzbget.png
  #    - homepage.href=http://192.168.2.100:6789
