version: '3.9'
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ./config/config.json:/config.json:ro
    restart: unless-stopped
