networks:
  traefik:
    external: true
  docker-socket-proxy:
    external: true

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
      - docker-socket-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      # - 443:443/tcp # Uncomment if you want HTTP3
      # - 443:443/udp # Uncomment if you want HTTP3
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN} # if using .env
      # TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/traefik/letsencrypt:/letsencrypt
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      ## docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=docker-socket-proxy"
      - "--providers.docker.endpoint=tcp://docker-socket-proxy:2375"
      ## entrypoints
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      ## create certresolver using cf dns
      - "--certificatesresolvers.cf-dns-resolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cf-dns-resolver.acme.dnschallenge.provider=cloudflare"
      ##- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment for debugging
      - "--certificatesresolvers.cf-dns-resolver.acme.email=fahim.shahreer95@gmail.com"
      - "--certificatesresolvers.cf-dns-resolver.acme.storage=/letsencrypt/acme.json"
      ## Add cf-dns-resolver as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.websecure.http.tls.certresolver=cf-dns-resolver
      - --entrypoints.websecure.http.tls.domains[0].main=fahimshahreer.com
      - --entrypoints.websecure.http.tls.domains[0].sans=*.fahimshahreer.com
      ## redirect all http traffic to https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    labels:
      - homepage.group=Management
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=http://192.168.2.100:8080

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.fahimshahreer.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      
